-- ============================================================
-- CHẠY TOÀN BỘ FILE NÀY (Supabase → SQL Editor → Run)
-- Sửa: sửa buổi tập, thêm buổi mới, điểm danh/CK lưu sau reload
-- ============================================================

-- ---------- PLAYERS: cột điểm danh, CK, buổi ----------
alter table public.players
  add column if not exists attended boolean not null default false,
  add column if not exists paid boolean not null default false,
  add column if not exists session_id bigint;

update public.players set session_id = 1 where session_id is null;

-- ---------- CONFIG: nhiều buổi, id tự tăng ----------
alter table public.config
  add column if not exists session_date date default current_date;

-- id tự tăng (nếu chưa có) — cần để "Buổi mới" hoạt động
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'config' and column_name = 'id'
  ) then
    begin
      alter table public.config alter column id add generated by default as identity;
    exception when others then
      null;
    end;
    perform setval(
      pg_get_serial_sequence('public.config', 'id'),
      coalesce((select max(id) from public.config), 1)
    );
  end if;
end $$;

-- FK players → config
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'players_session_id_fkey'
  ) then
    alter table public.players
      add constraint players_session_id_fkey
      foreign key (session_id) references public.config(id) on delete cascade;
  end if;
end $$;

-- Đảm bảo có ít nhất 1 buổi
insert into public.config (session_title, session_time, max_slots)
select 'Buổi tập cầu lông', '08:00 - 10:00', 12
where not exists (select 1 from public.config limit 1);

-- ---------- QUYỀN ----------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.players to anon, authenticated;
grant select, insert, update, delete on table public.config to anon, authenticated;

-- ---------- RLS PLAYERS ----------
alter table public.players enable row level security;

drop policy if exists "players_public_select" on public.players;
drop policy if exists "players_public_insert" on public.players;
drop policy if exists "players_public_update" on public.players;
drop policy if exists "players_public_delete" on public.players;

create policy "players_public_select"
  on public.players for select to anon, authenticated using (true);
create policy "players_public_insert"
  on public.players for insert to anon, authenticated with check (true);
create policy "players_public_update"
  on public.players for update to anon, authenticated using (true) with check (true);
create policy "players_public_delete"
  on public.players for delete to anon, authenticated using (true);

-- ---------- RLS CONFIG ----------
alter table public.config enable row level security;

drop policy if exists "config_public_select" on public.config;
drop policy if exists "config_public_insert" on public.config;
drop policy if exists "config_public_update" on public.config;
drop policy if exists "config_public_delete" on public.config;

create policy "config_public_select"
  on public.config for select to anon, authenticated using (true);
create policy "config_public_insert"
  on public.config for insert to anon, authenticated with check (true);
create policy "config_public_update"
  on public.config for update to anon, authenticated using (true) with check (true);
create policy "config_public_delete"
  on public.config for delete to anon, authenticated using (true);

-- Realtime (bỏ qua nếu đã bật)
do $$
begin
  alter publication supabase_realtime add table public.players;
exception when others then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.config;
exception when others then null;
end $$;
